services:
  server:
    build:
      context: .docker/nginx
    ports:
      - "8088:80"
    volumes:
      - ".:/var/www/html:delegated"
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - db
      - php
    networks:
      - app

  php:
    build:
      context: .docker/php
    volumes:
      - ".:/var/www/html:delegated"
    networks:
      - app

  db:
    build: .docker/mysql
    ports:
      - "3308:3306"
    volumes:
      - "${DB_VOLUME:-./dbdata}:/var/lib/mysql"
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    networks:
      - app

  npm:
    build:
      context: .docker/npm
    ports:
      - "3000:3000"
    volumes:
      - ".:/var/www/html:delegated"
    command: "npm run dev"
    networks:
      - app

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - "${REDIS_VOLUME:-./redisdata}:/data"
    networks:
      - app

networks:
  app:
      name: my-network
      driver: bridge

